# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 10:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, unique=True, verbose_name=b'\xe6\xa0\x87\xe9\xa2\x98')),
                ('link', models.CharField(default=b'', help_text=b"Cool URIs don't change", max_length=150, verbose_name=b'\xe9\x93\xbe\xe6\x8e\xa5')),
                ('snippet', models.CharField(default=b'', max_length=500, verbose_name=b'\xe6\x91\x98\xe8\xa6\x81')),
                ('content', models.TextField(verbose_name=b'\xe5\x86\x85\xe5\xae\xb9')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('publish_time', models.DateTimeField(null=True, verbose_name=b'\xe5\x8f\x91\xe8\xa1\xa8\xe6\x97\xb6\xe9\x97\xb4')),
                ('update_time', models.DateTimeField(verbose_name=b'\xe4\xbf\xae\xe6\x94\xb9\xe6\x97\xb6\xe9\x97\xb4')),
                ('status', models.CharField(choices=[(b'd', b'\xe8\x8d\x89\xe7\xa8\xbf'), (b'p', b'\xe5\xb7\xb2\xe5\x8f\x91\xe5\xb8\x83')], default=b'd', max_length=1, verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81')),
                ('is_public', models.BooleanField(default=True, verbose_name=b'\xe5\x85\xac\xe5\xbc\x80')),
                ('is_top', models.BooleanField(default=False, verbose_name=b'\xe7\xbd\xae\xe9\xa1\xb6')),
                ('access_count', models.IntegerField(default=1, editable=False, verbose_name=b'\xe6\xb5\x8f\xe8\xa7\x88\xe9\x87\x8f')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'\xe4\xbd\x9c\xe8\x80\x85')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, unique=True, verbose_name=b'\xe5\x90\x8d\xe7\xa7\xb0')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, unique=True, verbose_name=b'\xe5\x90\x8d\xe7\xa7\xb0')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name=b'\xe6\x89\x80\xe5\xb1\x9e\xe5\x88\x86\xe7\xb1\xbb'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text=b'\xe6\xa0\x87\xe7\xad\xbe', null=True, to='blog.Tag', verbose_name=b'\xe6\xa0\x87\xe7\xad\xbe\xe9\x9b\x86\xe5\x90\x88'),
        ),
    ]
